import {
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Ban,
  Bell,
  BookOpen,
  Brain,
  Bus,
  Calendar,
  Car,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Clock,
  Coffee,
  Copy,
  Download,
  Dumbbell,
  Film,
  Flame,
  FolderKanban,
  Gift,
  Globe,
  GraduationCap,
  Heart,
  HeartPulse,
  Home,
  KeyRound,
  LayoutDashboard,
  Loader,
  Menu,
  Mic,
  Moon,
  MoreHorizontal,
  Music,
  NotebookPen,
  Package,
  PawPrint,
  Pencil,
  PenLine,
  PiggyBank,
  Plane,
  Play,
  Plus,
  ReceiptText,
  ScrollText,
  Search,
  Settings,
  ShieldCheck,
  ShieldOff,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Square,
  Star,
  Sun,
  Target,
  Ticket,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  UserCheck,
  Users,
  UserX,
  Utensils,
  Wallet,
  Wind,
  Wrench,
  X,
  type LucideIcon,
} from "lucide-react";

const REGISTRY: Record<string, LucideIcon> = {
  Activity, ArrowDown, ArrowLeft, ArrowRight, ArrowUp, ArrowUpDown, Ban, Bell, BookOpen, Brain, Bus, Calendar, Car,
  Check, CheckCircle2, ChevronLeft, ChevronRight, Clock, Coffee, Copy, Download, Dumbbell, Film, Flame, FolderKanban,
  Gift, Globe, GraduationCap, Heart, HeartPulse,
  Home, KeyRound, LayoutDashboard, Loader, Menu, Mic, Moon, MoreHorizontal, Music, NotebookPen, Package, PawPrint, Pencil, PenLine,
  PiggyBank, Plane, Play, Plus, ReceiptText,
  ScrollText, Search, Settings, ShieldCheck, ShieldOff, Shirt, ShoppingBag, Smartphone, Sparkles, Square, Star, Sun, Target,
  Ticket, Trash2, TrendingDown, TrendingUp, TriangleAlert, UserCheck, Users, UserX,
  Utensils, Wallet, Wind, Wrench, X,
};

export function Icon({
  name,
  className,
  size = 18,
  strokeWidth = 2,
  style,
}: {
  name: string;
  className?: string;
  size?: number;
  strokeWidth?: number;
  style?: React.CSSProperties;
}) {
  const Cmp = REGISTRY[name] ?? Sparkles;
  return <Cmp className={className} size={size} strokeWidth={strokeWidth} style={style} />;
}
